Actually deny on missing docs
Fixes clippy error:

error: useless lint attribute
  --> src/lib.rs:27:1
   |
27 | #[deny(missing_docs)]
   | ^^^^^^^^^^^^^^^^^^^^^ help: if you just forgot a `!`, use: `#![deny(missing_docs)]`
   |
   = note: `#[deny(clippy::useless_attribute)]` on by default
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#useless_attribute