No need to check if a u64 is less than zero
Fixes clippy error:

error: this comparison involving the minimum or maximum element for this type contains a case that is always true or always false
  --> src/combine.rs:28:8
   |
28 |     if len2 <= 0 {
   |        ^^^^^^^^^
   |
   = note: `#[deny(clippy::absurd_extreme_comparisons)]` on by default
   = help: because `0` is the minimum value for this type, the case where the two sides are not equal never occurs, consider using `len2 == 0` instead
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#absurd_extreme_comparisons