Remove unused constant K6
It only ever got dropped, which does nothing for types implementing Copy
Fixes clippy error:

error: calls to `std::mem::drop` with a value that implements `Copy`. Dropping a copy leaves the original intact.
   --> src/specialized/pclmulqdq.rs:147:5
    |
147 |     drop(K6);
    |     ^^^^^^^^
    |
    = note: `#[deny(clippy::drop_copy)]` on by default
note: argument has type i64
   --> src/specialized/pclmulqdq.rs:147:10
    |
147 |     drop(K6);
    |          ^^
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#drop_copy